name: on pull request workflow
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  flutter_test:
    name: flutter analyze & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          version: "3.3.10"
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"